spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
    
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.du.SpringBootTest1.bean

lin:
  kaptchaswich: false

      